name: GPT Translate
 
on:
  issue_comment:
    types: [created]
 
jobs:
  gpt_translate:
    if: |
      github.actor == 'thias15' &&
      contains(github.event.comment.body, '/gpt-translate') || 
      contains(github.event.comment.body, '/gt')
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
 
      - name: Run GPT Translate
        uses: 3ru/gpt-translate@master
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          model: gpt-4o
          prompt: |
            Please translate the README source file to {targetLanguage}. \
              Make the translation sound as natural as possible. \
              Keep the HTML snippet in the same place as in the source file or add it below the top heading and keep existing languages. \
              {targetLanguage} should be shown in plaintext and other languages as links to the corresponding README files using the Language Culture Name. \
              For example, for English, Chinese and German the top of the German README should look like this:
              <p align="center">
                <a href="README.md">English</a> |
                <a href="README.zh-CN.md">简体中文</a> |
                <span>Deutsch</span>
              </p>
              Do NOT add ``` tags to the HTML snippet.
