name: GPT Review

on:
  issue_comment:
    types: [created]

jobs:
  gpt_review:
    if: |
      github.actor == 'thias15' &&
      contains(github.event.comment.body, '/gpt-review') || 
      contains(github.event.comment.body, '/gr')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run GPT Code Review
        uses: mattzcarey/code-review-gpt@v0.1.8
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: 'gpt-4o'
          GITHUB_TOKEN: ${{ github.token }}
